name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/proyecto/LogisimWeb/
          git pull origin main
          git status
          docker stop logisimweb
          docker rm logisimweb
          docker build -t logisimweb-image .
          docker run -dit -p 5014:3000 --restart unless-stopped --name logisimweb logisimweb-image
          
